// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ExampleGet implements GET /example operation.
//
// GET /example
func (UnimplementedHandler) ExampleGet(ctx context.Context, params ExampleGetParams) (r string, _ error) {
	return r, ht.ErrNotImplemented
}

// ExamplePost implements POST /example operation.
//
// POST /example
func (UnimplementedHandler) ExamplePost(ctx context.Context, req *ExamplePostReq) (r string, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrRespStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrRespStatusCode) {
	r = new(ErrRespStatusCode)
	return r
}
