/*
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExampleBody struct {
	Param1 int64 `json:"param1"`
	Param2 int64 `json:"param2,omitempty"`
}
