openapi: 3.0.3
info:
  title: example
  version: "1.0"
servers:
- url: /
paths:
  /example:
    get:
      parameters:
      - name: param1
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: param2
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: あ
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/example_body"
        required: true
      responses:
        "200":
          description: あ
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
components:
  schemas:
    example_body:
      required:
      - param1
      type: object
      properties:
        param1:
          type: integer
          format: int64
        param2:
          type: integer
          format: int64
