openapi: 3.0.3
info:
  title: example
  version: "1.0"
servers:
- url: /
paths:
  /example:
    get:
      parameters:
      - explode: true
        in: query
        name: param1
        required: true
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: param2
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: あ
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_example_post_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: あ
components:
  schemas:
    _example_post_request:
      properties:
        param1:
          format: int64
          type: integer
        param2:
          format: int64
          type: integer
      required:
      - param1
      type: object
